services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
